services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  order-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${ORDER_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
      POSTGRES_DB: ${ORDER_DB_NAME}
    volumes:
      - ./order-service/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "55432:5432"

  payment-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PAYMENT_DB_USER}
      POSTGRES_PASSWORD: ${PAYMENT_DB_PASSWORD}
      POSTGRES_DB: ${PAYMENT_DB_NAME}
    volumes:
      - ./payment-service/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "55433:5432"

  payment-service:
    build: ./payment-service
    environment:
      DATABASE_URL: ${PAYMENT_DATABASE_URL}
      GRPC_PORT: ${PAYMENT_GRPC_PORT}
      RABBITMQ_URL: ${RABBITMQ_URL}
    ports:
      - "50051:50051"
    depends_on:
      rabbitmq:
        condition: service_healthy
      payment-db:
        condition: service_started
    restart: on-failure
    stop_grace_period: 10s

  notification-service:
    build: ./notification-service
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      REDIS_ADDR: ${REDIS_ADDR}
      PROVIDER_MODE: ${PROVIDER_MODE}
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    stop_grace_period: 10s

  order-service:
    build: ./order-service
    environment:
      DATABASE_URL: ${ORDER_DATABASE_URL}
      PAYMENT_SERVICE_ADDR: ${PAYMENT_SERVICE_ADDR}
      REST_PORT: ${ORDER_REST_PORT}
      GRPC_PORT: ${ORDER_GRPC_PORT}
      REDIS_ADDR: ${REDIS_ADDR}
    ports:
      - "8080:8080"
      - "50052:50052"
    depends_on:
      order-db:
        condition: service_started
      payment-service:
        condition: service_started
      redis:
        condition: service_healthy
    restart: on-failure
    stop_grace_period: 10s